Unbreak the MSVC build. It was broken since [4854aa11], which produced warning C4090 about different const qualifiers, which in turn triggered error C2220 (warnings treated as errors). For an unknown reason GitHub Actions does not treat warnings as errors on MSVC (would be nice if it did!).